"""Facade pattern, REPL interface, Decorators, and Colorama UI."""

import sys
from colorama import init, Fore, Style
from app.input_validators import validate_number
from app.calculation import OperationFactory, CalculateCommand, CommandInvoker
from app.history import HistoryManager, AutoSaveObserver
from app.logger import LoggingObserver
from app.exceptions import CalculatorException

# Initialize Colorama for cross-platform colored terminal output
init(autoreset=True)


class CalculatorFacade:
    """Facade that simplifies interaction with calculator subsystems."""

    def __init__(self):
        # Manages calculation history
        self.history = HistoryManager()

        # Register observers that react to history updates
        self.history.add_observer(AutoSaveObserver())
        self.history.add_observer(LoggingObserver())

        # Invoker responsible for executing command objects
        self.invoker = CommandInvoker()

    def calculate(self, op_name: str, a_str: str, b_str: str):
        """Validate inputs, execute calculation, and record history."""
        try:
            # Convert and validate user input
            a = validate_number(a_str)
            b = validate_number(b_str)

            # Create a command object for the requested operation
            command = CalculateCommand(op_name, a, b)

            # Execute the command via the invoker
            result = self.invoker.execute_command(command)

            # Store the result in history
            self.history.add_record(op_name, a, b, result)

            # Format output (remove .0 if integer)
            display_result = int(result) if result.is_integer() else result
            print(Fore.GREEN + f"  🟢 Result: {display_result}")

        except CalculatorException as e:
            # Handle known calculator-related errors
            print(Fore.RED + f"  🔴 Error: {e}")

        except Exception as e:
            # Catch unexpected runtime errors
            print(Fore.RED + f"  🔴 Unexpected Error: {e}")


# ==========================================
# DECORATOR PATTERN
# ==========================================

def dynamic_help(func):
    """Decorator that dynamically generates the help menu."""

    def wrapper(*args, **kwargs):
        # Retrieve available math operations from the factory
        available_ops = ", ".join(OperationFactory._operations.keys())

        # Display help menu with available commands
        print(Fore.CYAN + "\n=== HELP MENU ===")
        print(Fore.YELLOW + "📌 Type an operation and two numbers (e.g., 'add 5 10')")
        print(Fore.GREEN + f"📌 Math commands: {available_ops}")
        print(Fore.MAGENTA + "📌 Data commands: history, clear, undo, redo, save, load")
        print(Fore.CYAN + "=================\n")

        return func(*args, **kwargs)

    return wrapper


@dynamic_help
def show_help():
    """Displays the help menu (generated by decorator)."""
    pass


# ==========================================
# REPL (Read-Eval-Print Loop)
# ==========================================

def repl():
    """Start the interactive calculator session."""
    calc = CalculatorFacade()

    # Display application header
    print(Fore.CYAN + "\n" + "=" * 45)
    print(Fore.WHITE + Style.BRIGHT + " 🚀  ENHANCED PROFESSIONAL CALCULATOR")
    print(Fore.CYAN + "=" * 45)
    print(Fore.YELLOW + " Type 'help' for commands or 'exit' to quit.")
    print(Fore.CYAN + "-" * 45)

    while True:
        try:
            # Read user input
            user_input = input(Fore.BLUE + "\n[Calculator] ➜ " + Style.RESET_ALL).strip().lower()
        except EOFError:
            break

        if not user_input:
            continue

        parts = user_input.split()
        command = parts[0]

        # Exit command
        if command == 'exit':
            print(Fore.YELLOW + "  👋 Goodbye!\n")
            break

        # Display help menu
        elif command == 'help':
            show_help()

        # Show calculation history
        elif command == 'history':
            calc.history.display()

        # Clear stored history
        elif command == 'clear':
            calc.history.clear()
            print(Fore.YELLOW + "  🧹 History cleared.")

        # Undo last history change
        elif command == 'undo':
            if calc.history.undo():
                print(Fore.YELLOW + "  ⏪ [Undo] Reverted to previous state.")
            else:
                print(Fore.RED + "  ⚠️  [Undo] Cannot undo. You are at the beginning of your history.")

        # Redo last undone change
        elif command == 'redo':
            if calc.history.redo():
                print(Fore.YELLOW + "  ⏩ [Redo] Restored state.")
            else:
                print(Fore.RED + "  ⚠️  [Redo] Cannot redo. You are at the latest state.")

        # Manually save history to CSV
        elif command == 'save':
            if calc.history.save_history():
                print(Fore.GREEN + "  💾 History manually saved to CSV.")
            else:
                print(Fore.RED + "  🔴 Error saving history.")

        # Load history from CSV
        elif command == 'load':
            if calc.history.load_history():
                print(Fore.GREEN + "  📂 History manually loaded from CSV.")
            else:
                print(Fore.RED + "  ⚠️  No existing history found to load.")

        # Mathematical operations handled by the factory
        elif command in OperationFactory._operations.keys():

            # Direct input: operation x y
            if len(parts) == 3:
                calc.calculate(command, parts[1], parts[2])

            # Interactive input if numbers were omitted
            elif len(parts) == 1:
                a = input("    ↳ Enter first number: ")
                b = input("    ↳ Enter second number: ")
                calc.calculate(command, a, b)

            else:
                print(Fore.RED + "  ⚠️  Usage: <operation> <x> <y>")

        # Unknown command handler
        else:
            print(Fore.RED + f"  ❓ Unknown command '{command}'. Type 'help' for options.")